- name: dnf - Install ad_auth required tools
  dnf: 
    name: python-pip,python3-libselinux,realmd,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,python3-pip,sudo
    state: present
  become: yes

- name: Install pexpect using pip
  pip:
    name: pexpect
  become: yes

- name: Check if machine is bound
  shell: /bin/bash -c "realm list | grep sssd"
  register: realmd_bound
  changed_when: false
  ignore_errors: true
  become: yes

- debug: 
    msg: "{{ realmd_bound }}"

# The SSSD service fails if the template was already joined
# If realm list is populated the playbook leaves the domain and rejoins in the next step
- name: Leave AD if already joined
  shell: /bin/bash -c "/usr/sbin/realm leave ia.wd.org"
  when: realmd_bound is search ("client-software:\ sssd")
  become: yes

- name: Join system to AD
  expect:
    command: /bin/bash -c "/usr/sbin/realm join --user={{ ad_user }} ia.wd.org"
    responses:
      Password for *: "{{ ad_pass }}"
  when: realmd_bound is search ("sssd")
  become: yes

- name: Add line to sssd.conf
  lineinfile: 
    dest: /etc/sssd/sssd.conf
    line: 'default_domain_suffix = ia.wd.org'
    insertafter: '^\[sssd\]'
  notify:
    - restart sssd  
  become: yes

- name: Add override homedir to sssd.conf
  lineinfile: 
    dest: /etc/sssd/sssd.conf
    line: 'override_homedir=/home/%d/%u'
    insertafter: '^\[domain/ia.wd.org\]'
  notify:
    - restart sssd
  become: yes

- name: Make ia.wd.org home directory
  file:
    path: /home/ia.wd.org
    state: directory
  become: yes

- name: Restrict access based on specific ad group
  command: /bin/bash -c "/usr/sbin/realm permit -g LinuxAdmin@ia.wd.org"
  become: yes

- name: Add AD group to sudoers
  lineinfile:
    dest: /etc/sudoers
    line: '%LinuxAdmin@ia.wd.org        ALL=(ALL)       ALL'
    insertafter: '^%wheel'
  become: yes

