
- name: dnf - Install ad_auth required tools
  dnf: 
    name: epel-release,python3-pip,python3-libselinux,realmd,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,python3-pip,sudo
    state: latest
  become: yes

- name: install python-setuptools
  package:
    name: python-setuptools
    state: present

- name: Install pexpect using pip
  vars: 
    ansible_python_interpreter: /usr/bin/python2
  pip:
    name: pexpect
  become: yes
  
- name: Check if machine is bound
  shell: /bin/bash -c "realm list | grep sssd"
  register: realmd_bound
  changed_when: false
  ignore_errors: true
  become: yes

- debug: 
    msg: "{{ realmd_bound }}"

# The SSSD service fails if the template was already joined
# If realm list is populated the playbook leaves the domain and rejoins in the next step
- name: Leave AD if already joined
  shell: /bin/bash -c "/usr/sbin/realm leave fkl-lab.internal"
  when: realmd_bound is search ("client-software:\ sssd")
  become: yes

- name: Join system to AD
  expect:
    command: /bin/bash -c "/usr/sbin/realm join --user={{ ad_user }} fkl-lab.internal"
    responses:
      Password for *: "{{ ad_pass }}"
  vars:
    ansible_python_interpreter: /usr/bin/python2
  
  when: realmd_bound is search ("sssd")
  become: yes

- name: Add line to sssd.conf
  lineinfile: 
    dest: /etc/sssd/sssd.conf
    line: 'default_domain_suffix = fkl-lab.internal'
    insertafter: '^\[sssd\]'
  notify:
    - restart sssd  
  become: yes

- name: Add override homedir to sssd.conf
  lineinfile: 
    dest: /etc/sssd/sssd.conf
    line: 'override_homedir=/home/%d/%u'
    insertafter: '^\[domain/fkl-lab.internal\]'
  notify:
    - restart sssd
  become: yes

- name: Make ia.wd.org home directory
  file:
    path: /home/fkl-lab.internal
    state: directory
  become: yes

- name: Restrict access based on specific ad group
  command: /bin/bash -c "/usr/sbin/realm permit -g LinuxAdmin@fkl-lab.internal"
  become: yes

- name: Add AD group to sudoers
  lineinfile:
    dest: /etc/sudoers
    line: '%LinuxAdmin@fkl-lab.internal        ALL=(ALL)       ALL'
    insertafter: '^%wheel'
  become: yes

