- name: Populate service facts
  service_facts:

- name: dnf - Install CIFS-Utils
  dnf:
    name: 'cifs-utils'
    state: present

- name: Create FireEye Installer Directory
  file:
    path: /tmp/fireeye
    state: directory
  when: "'xagt.service' not in services"

- name: Create Mount Point for FireEye Share
  file:
    path: /mnt/fireeye
    state: directory
  when: "'xagt.service' not in services"

- name: Mount FireEye CIFS Share
  mount:
    state: "mounted"
    fstype: "cifs"
    name: /mnt/fireeye
    src: "//iwdna1a/installs/FireEye"
    opts: "user={{ ad_user }},password={{ ad_pass }},file_mode=0644,dir_mode=0755,gid=root,uid=root"
  when: "'xagt.service' not in services"

- name: Extract fireeye.tgz into /tmp/fireeye
  ansible.builtin.unarchive:
    src: /mnt/fireeye/Linux/IMAGE_HX_AGENT_LINUX_33.46.6.tgz
    dest: /tmp/fireeye
    remote_src: yes
  when: "'xagt.service' not in services"

- name: dnf - Install FireEye package
  dnf:
     name: /tmp/fireeye/xagt-33.46.6-1.el7.x86_64.rpm
     state: present
     disable_gpg_check: yes
  when: "'xagt.service' not in services"

- name: Run command to register agent_config.json
  ansible.builtin.command: /opt/fireeye/bin/xagt -i /tmp/fireeye/agent_config.json
  when: "'xagt.service' not in services"

- name: Populate service facts after install to validate
  service_facts:

- name: Start Fireeye service
  ansible.builtin.service:
    name: xagt
    state: started
  when: "'xagt.service' in services"

- name: Unmount FireEye Share
  mount:
    path: /mnt/fireeye/
    state: unmounted

- debug:
    msg: FireEye installed!
  when: "'xagt.service' in services"
